### PR TITLE
Set support language-worker settings in the host start command line. …

### LINKED ISSUE #521: Enable Python debug port
For VS Code to use /cc @nturinski @fiveisprime

### PR DESCRIPTION
**Pull request by ahmelsayed**
…Closes #521

### CODE REVIEW

**Comment by ahmelsayed** [comment]
@pragnagopa but java is `debug`, right?

**Comment by pragnagopa** [comment]
Correct. Java still uses different configuration model https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/Configuration/JavaWorkerProvider.cs haven’t update java yet

**Comment by ahmelsayed** [comment]
Thanks Pragna. I updated the map.

**Comment by vfedonkin** [comment]
I have some issue with this code on my dev machine:
return new Dictionary<string, string>
                {
                    { _map[workerRuntime], value }
                };

 _map[workerRuntime] can be equal to string.Empty ("") and this will fail since Environment.SetEnvironmentVariable can't set empty variable.

**Comment by ahmelsayed** [comment]
Thanks @vfedonkin 
Fixed in https://github.com/Azure/azure-functions-core-tools/commit/cad3ac5ac6da524902a2a45fddea5dc4c6a9f1c3

**Pull request merged**
