### PR TITLE
Aegpoadan/add-key-vault-references-v3.x

### PR DESCRIPTION
**Pull request by aegpoadan**
https://github.com/Azure/azure-functions-core-tools/issues/933

https://github.com/Azure/azure-functions-host/issues/3907

Supports both @Microsoft.KeyVault syntaxes.

### CODE REVIEW

**Comment by aegpoadan** [comment]
Based off of https://github.com/Azure/azure-functions-core-tools/pull/2258

I would like to see this functionality added to the Azure Functions Core Tools and got tired of waiting for the above PR to be rebased. Made a few tweaks to clean up the code.

@mattchenderson @fabiocav

**Comment by anthonychu** [comment]
Thanks. @michaelpeng36

**Review by michaelpeng36 — CHANGES_REQUESTED** [review]
The changes so far look good to me. However, this needs to add `"Azure.Security.KeyVault.*"` to the `thirdPartyBinaries` array in `Settings.cs`.

**Comment by michaelpeng36** [comment]
@aegpoadan thank you for the contribution, and apologies for the delayed review. Minor changes are needed for this to be merged, but the changes directly pertaining to KeyVault references seem correct to me. Once this branch is merged, would you be able to port the changes over to `v4.x`?

**Comment by aegpoadan** [comment]
Yep! I can port this change over to v4.x once this PR is merged.

**Comment by aegpoadan** [comment]
@michaelpeng36 I've added `"Azure.Security.KeyVault.*"` to `Settings.cs`

**Review by michaelpeng36 — APPROVED** [review]
LGTM

**Comment by aegpoadan** [comment]
@michaelpeng36 I've created a new PR for v4.x here: https://github.com/Azure/azure-functions-core-tools/pull/2924

**Pull request merged**
