### PR TITLE
Change ESRP connection name from hard coded to variable.

### PR DESCRIPTION
**Pull request by khkh-ms**
### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [ ] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by arroyc — APPROVED** [review]

**Comment by arroyc** [comment]
i see the test failures for this, can we please make sure tests are doing okay before merging this PR

**Comment by khkh-ms** [comment]
\azp run

**Comment by jviau** [comment]
@khkh-ms is this PR needed since we are migrating to 1ES?

**Comment by jviau** [comment]
Closing for now.

**Pull request closed without merging**
