### PR TITLE
updating host to 3.0.12930

### PR DESCRIPTION
**Pull request by brettsam**

### CODE REVIEW

**Comment by brettsam** [comment]
@ahmelsayed / @ankitkumarr -- any ideas on this test failure? https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=3068&view=ms.vss-test-web.build-test-results-tab&runId=1006034&resultId=100051&paneView=debug

**Comment by ahmelsayed** [comment]
I'll fix it in another commit.

**Comment by ahmelsayed** [comment]
Looks like you got the test too. Thanks @brettsam

**Comment by brettsam** [comment]
Yeah, @ankitkumarr told me what the issue was. Thanks for the quick response!

**Pull request merged**
