### PR TITLE
Update Microsoft.ApplicationInsights to version 2.20.1

### PR DESCRIPTION
**Pull request by Francisco-Gamino**
### Issue describing the changes in this PR

Resolves https://github.com/Azure/azure-functions-core-tools/issues/3183.

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by ejizba — APPROVED** [review]

**Comment by czb182** [comment]
I don’t even see application insights 2.20.1 on Nuget, it’s either 2.20.0 or 2.21.0

**Comment by Francisco-Gamino** [comment]
> I don’t even see application insights 2.20.1 on Nuget, it’s either 2.20.0 or 2.21.0

@czb182 --  Here is the latest version: https://www.nuget.org/packages/Microsoft.ApplicationInsights
image

**Comment by czb182** [comment]
Yeah, just confused because the commit has "2.20.1", when I would have expected 2.21.0

**Comment by Francisco-Gamino** [comment]
> Yeah, just confused because the commit has "2.20.1", when I would have expected 2.21.0

@czb182 -- Good point. I am not logging SME, so I am not sure on why we are currently using this version. However, for testing, we keep parity between the Functions Host and the Core Tools and this is the latest version referenced in the Functions Host. When this parity is broken, we start to see failures in our builds, and this is what this PR is fixing.

If you are running into into issues using this version of Microsoft.ApplicationInsights, please open an issue here: https://github.com/Azure/azure-functions-host/issues.

**Comment by czb182** [comment]
I checked azure functions runtime and they updated to 2.21.0, not 2.20.1

https://github.com/Azure/azure-functions-host/pull/8838/files

**Pull request merged**
