### PR TITLE
Adding timeoutInMinutes

### PR DESCRIPTION
**Pull request by alrod**
need to extend build timeout to pass build on release_3.0(60minutes by default)

### CODE REVIEW

**Comment by Francisco-Gamino** [comment]
Are these the only lines you are adding? 
```
jobs:
- job: Default
  timeoutInMinutes: "90"
```

**Comment by alrod** [comment]
> Are these the only lines you are adding?
> 
> ```
> jobs:
> - job: Default
>   timeoutInMinutes: "90"
> ```

yes, I also apply "tab" to the content below `timeoutInMinutes: "90"` that is why the diff looks weird

**Comment by alrod** [comment]
changed base branch to v3.x as it can makes release process problematic in future. The automation won't be able to merge v3.x to release later and we will have to manually fix the branch (thanks @ankitkumarr )

**Review by Francisco-Gamino — APPROVED** [review]
LGTM

**Review by ankitkumarr — APPROVED** [review]

**Pull request merged**
