### PR TITLE
Handle empty settings in local.setting.json

### LINKED ISSUE #1258: Blank value in local settings ignored
I have a value in my settings `QueuePrefix` which I'm using to prefix my queue names so I can test against different environments locally.

I'm using this in my queue triggers locally: 
```csharp
public static Task Run([QueueTrigger("%QueuePrefix%my-queue-name", Connection = "Storage")] ...
```

This was working so I could test one environment without a prefix and one with.  I'm not sure what has changed (possibly since updating to V2) but this no longer seems to work with blank values.

I get this misleading error when I start the functions app:

```
Skipping 'QueuePrefix' from local settings as it's already defined in current environment variables.
```

And then the following error when it tries to index my function:
```
[08/04/2019 08:45:15] Error indexing method 'MyFunction'
[08/04/2019 08:45:15] Microsoft.Azure.WebJobs.Host: Error indexing method 'MyFunction'. Microsoft.Azure.WebJobs.Host: '%QueuePrefix%' does not resolve to a value.
```

### PR DESCRIPTION
**Pull request by ahmelsayed**
Closed #1258

### CODE REVIEW

**Comment by hisuwh** [comment]
Any idea when this will be published

**Comment by ahmelsayed** [comment]
It should be in current release `2.7.1149`.

**Comment by hisuwh** [comment]
How do I get that? Functions runtime usually tells me if there are updates when I run it from VS

**Comment by ahmelsayed** [comment]
Oh sorry I didn't push that version to Visual Studio because it had no runtime changes. I didn't realize you were using VS. I'll push it out today.

**Comment by hisuwh** [comment]
Legend. Thank you

**Comment by soninaren** [comment]
@hisuwh the release is complete. Please close all instances of VS and open them again to fetch new version of core tools.

**Comment by hisuwh** [comment]
Running functions I still get this error:
```
Azure Functions Core Tools (2.7.1158 Commit hash: f2d2a2816e038165826c7409c6d10c0527e8955b)
Function Runtime Version: 2.0.12438.0
```

image

**Pull request merged**
