### PR TITLE
Update PowerShellWorker to v3.0.279 and v3.0.283

### PR DESCRIPTION
**Pull request by AnatoliB**
PowerShell worker release notes:
- https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.279
- https://github.com/Azure/azure-functions-powershell-worker/releases/tag/v3.0.283

### CODE REVIEW

**Comment by AnatoliB** [comment]
I keep getting this error from the build:

> Unhandled Exception: System.Exception: sigcheck.exe test failed. Following files are unsigned: 
d:\a\1\s\artifacts\presigntest\min.win-x86\System.Interactive.Async.dll
   at Build.BuildSteps.TestPreSignedArtifacts() in D:\a\1\s\build\BuildSteps.cs:line 301
   at Build.Orchestrator.Run() in D:\a\1\s\build\Orchestrator.cs:line 69
   at Build.Program.Main(String[] args) in D:\a\1\s\build\Program.cs:line 14

https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=5302&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=036ed663-514a-59f3-0c88-23d2cf182147&l=343

@soninaren Do you have any idea? Asking you because I can see your recent signing-related commit. The new PS worker packages don't even have a `System.Interactive.Async.dll` file, signed or unsigned.

**Comment by soninaren** [comment]
@AnatoliB, Can you build core tools locally and check if that file is signed? I checked the file in the prod CLI. Looks like that is signed.

I don't see this file in the list of binaries to sign.  https://github.com/Azure/azure-functions-core-tools/blob/anatolib/update-ps-worker-v3/build/Settings.cs#L144-L226

**Comment by AnatoliB** [comment]
> @AnatoliB, Can you build core tools locally and check if that file is signed? I checked the file in the prod CLI. Looks like that is signed.

@soninaren I've built the project locally: the file is signed.

**Comment by soninaren** [comment]
i see let me check why sigcheck is failing.

**Comment by AnatoliB** [comment]
Closing this PR as https://github.com/Azure/azure-functions-core-tools/pull/2007 makes it redundant

**Pull request closed without merging**
