### PR TITLE
Update Dotnet Static Template to 3.1.1788

### PR DESCRIPTION
**Pull request by TsuyoshiUshio**
The current template doesn't include 

The latest version 3.1.1788 includes RabbitMQ and Kafka Extension

Commit:
https://github.com/Azure/azure-functions-templates/tree/31a837d9ec5759205b71b0a083fc4165cdb87d45 
https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=12411&view=results

### CODE REVIEW

**Review by pragnagopa — APPROVED** [review]

**Comment by TsuyoshiUshio** [comment]
The root cause of the CI fail is the template zip is not there. https://functionscdn.azureedge.net/public/TemplatesApi/3.1.1786.zip
`3.1.1786` has it but not for `3.1.1788`

**Comment by TsuyoshiUshio** [comment]
I rollback the `TemplateJsonVersion`. That is for Static Template (that is deprecated) We don't need to update it for dotnet.

**Review by soninaren — APPROVED** [review]

**Comment by michaelpeng36** [comment]
Closing stale PR, as the issue is addressed by PR #3016

**Pull request closed without merging**
