### PR TITLE
Update KEDA to version v2.5

### PR DESCRIPTION
**Pull request by JorTurFer**
We have released KEDA v2.5 and this updates the manifest to use it

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [x] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [x] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Tagging @ahmelsayed and myself to help

**Review by michaelpeng36 — APPROVED** [review]
LGTM

**Comment by JorTurFer** [comment]
is the problem related with the change?

**Comment by michaelpeng36** [comment]
No, the failure does not appear relevant to the changes made here.

**Review by tomkerkhove — APPROVED** [review]

**Comment by michaelpeng36** [comment]
@JorTurFer thanks for your contribution! Could you port these changes over to the `v4.x` branch?

**Comment by JorTurFer** [comment]
sure, I will add there also :)

**Pull request merged**
