### PR TITLE
Added --skip-npm-install option for NodeJS V4 programming model

### LINKED ISSUE #3332: Allow skipping NPM install of node functions with model v4
When initializing a new function app with node and model v4, an NPM install always runs.
(e.g., running the command `func init my-cool-name --worker-runtime node --language typescript --model V4`)

Would be great to have a flag to skip this step, something like `--skip-npm-install` or something like that.

### PR DESCRIPTION
**Pull request by AlexPshul**
### Issue describing the changes in this PR
This really helps in mono-repo scenarios in which the NPM install is not actually needed but takes a significant time to initialize a new project. (A proper warning is added if NPM installation is skipped)
resolves #3332 

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by AlexPshul** [comment]
@microsoft-github-policy-service agree

**Review by khkh-ms — APPROVED** [review]

**Comment by AlexPshul** [comment]
Hi @khkh-ms @mattchenderson ,
Is there anything else I need to do in this PR? Or is it ready for merging?

**Comment by AlexPshul** [comment]
Hi @khkh-ms for continuing the process on this.
I see that the build failed on 2 items and it seems to be unrelated to my changes:

- Azure.Functions.Cli.Tests.E2E.InitTests.init_with_Dockerfile(workerRuntime: "node", version: "4")
- Azure.Functions.Cli.Tests.E2E.DeploymentTests.RemoteBuildPythonFunctionApp

Is it something I need to handle on my side?
Is there anything I can help with to help with the merge?

**Pull request merged**
