### PR TITLE
Added PartitionCount lookup from host.json - moved from dev

### PR DESCRIPTION
**Pull request by gorillapower**
### Issue describing the changes in this PR

When deleting a Task hub via the CLI, the default hardcoded partition count is used (currently 4). This means that only the default number of queues are deleted, resulting in orphaned queues in the storage account.

This pull request uses the partition count specified in the host.json if it is present.

### Pull request checklist

* [ X] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ X] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by michaelpeng36 — APPROVED** [review]
LGTM

**Comment by michaelpeng36** [comment]
@gorillapower Thanks for the contribution! Could you also port this change to the `v3.x` branch?

**Comment by gorillapower** [comment]
> @gorillapower Thanks for the contribution! Could you also port this change to the `v3.x` branch?

@michaelpeng36  I have added #3027

**Pull request merged**
