### PR TITLE
white listing building only v1.x branch, bumping seed version for devops

### PR DESCRIPTION
**Pull request by soninaren**

### CODE REVIEW

**Comment by brettsam** [comment]
Do we know why this build failed?

**Comment by soninaren** [comment]
> Do we know why this build failed?

I thought it was because of variables not being available for pr.

**Comment by brettsam** [comment]
They're available now... so in theory this should be working.

**Comment by ahmelsayed** [comment]
Thanks @brettsam and @soninaren for getting this to work! Can you also get the artifacts to be available after a run? I'm not sure what the syntax for that is in azure-pipelines.yml. I think that's the last thing we need before merging this.

**Comment by ahmelsayed** [comment]
actually I just noticed there are 2 PRs with the same name. Did you mean to close the other one?

**Comment by brettsam** [comment]
We paused this while we work out some kinks over in naren's fork. We'll get a real PR here and clean this up shortly... I think I just figured out the last issue we were having.

**Comment by ahmelsayed** [comment]
Sounds good. Thanks @brettsam

**Comment by brettsam** [comment]
Okay I think we got it. That last build has artifacts.

**Pull request merged**
