### PR TITLE
Update templates versions

### LINKED ISSUE #3405: build/Settings.cs needs to have Templates versions updated
Hi,
At the moment here:
https://github.com/Azure/azure-functions-core-tools/blob/v4.x/build/Settings.cs#L22
we have Isolated Template version used as `4.0.2288`

And that is utilized then here:
https://github.com/Azure/azure-functions-core-tools/blob/v4.x/build/Settings.cs#L166
i.e. via:
`public static readonly string DotnetIsolatedItemTemplates = $"https://www.nuget.org/api/v2/package/Microsoft.Azure.Functions.Worker.ItemTemplates/{DotnetIsolatedItemTemplatesVersion}";`

While for `Microsoft.Azure.Functions.Worker.ItemTemplates` in here:
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ItemTemplates#versions-body-tab

we have latest version as `4.0.2678`. So potentially some bump up is needed assuming it's passing all related builds/pipeline.

### PR DESCRIPTION
**Pull request by andrejusc**
### Issue describing the changes in this PR

resolves #3405

### Pull request checklist

* [X] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [X] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by khkh-ms** [comment]
I am going to close the PR to try something. I will create a new PR.

**Comment by andrejusc** [comment]
@khkh-ms - so what next here?

**Comment by khkh-ms** [comment]
Closing it as both dotnet and dotnet isolated templates have been updated to 4.0.2738.

**Comment by khkh-ms** [comment]
Closing it as both dotnet and dotnet isolated templates have been updated to 4.0.2738.

**Pull request closed without merging**
