### PR TITLE
Replace broken unzipper with extract-zip

### LINKED ISSUE #3335: When installing Azure Functions Core Tools under latest Node.js version, the extracted files are corrupt
Underlying issue: https://github.com/ZJONSSON/node-unzipper/issues/271

```
PS C:\Users\hajek> node --version
v18.16.0
```

The issue happens when https://github.com/Azure/azure-functions-core-tools/blob/v4.x/src/Azure.Functions.Cli/npm/lib/install.js is triggered.

### PR DESCRIPTION
**Pull request by hajekj**
This PR fixes an issue with `postinstall` execution script which extracts the Functions CLI tools, however in a corrupt state due to an issue occurring in https://github.com/ZJONSSON/node-unzipper/issues/271 

**These changes need to be backported to v3.x and eventually other branches. Which branches should be part of the backport?**

### Issue describing the changes in this PR

resolves #3335

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [] Otherwise: Documentation issue linked to PR
* [ ] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by ejizba — APPROVED** [review]
Looks good to me, thanks!

> These changes need to be backported to v3.x and eventually other branches. Which branches should be part of the backport?

v3 reached [end-of-life last December](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=v4&pivots=programming-language-javascript), so we're not doing new releases for it.

**Comment by rachel-wright** [comment]
any ETA on when this fix will be published? I don't see any installation that installs a version higher than 4.5095

**Comment by ejizba** [comment]
Should be any day now - I would guess a week at the latest

**Pull request merged**
