### PR TITLE
Correcting in-process model tag format

### PR DESCRIPTION
**Pull request by mattchenderson**
Updates base image tag for scaffolded Dockerfile to use the modified format.

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by khkh-ms — APPROVED** [review]

**Comment by khkh-ms** [comment]
The package update is in another PR. If the PR is urgent, please include this commit in your branch so that it passes the build. 
https://github.com/Azure/azure-functions-core-tools/pull/3701/commits/fef483a206e44f86063ad3c40a4f0158936189b6

**Comment by fabiocav** [comment]
@khkh-ms those changes shouldn't be combined here. Do you already have a PR for this? I see the commit you've linked to, but I don't see a PR.

**Comment by khkh-ms** [comment]
Hi @mattchenderson I assume that you have done the necessary changes with the update docker file. Please confirm.

**Comment by khkh-ms** [comment]
Let me create a small PR from the commit. It is actually part of the different longer PR.

**Pull request merged**
