### PR TITLE
feat: Upgrade to KEDA v2.6

### PR DESCRIPTION
**Pull request by tomkerkhove**
https://github.com/kedacore/keda/releases/tag/v2.6.0

### Issue describing the changes in this PR

N/A

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
  * [x] Otherwise: Backport tracked by issue/PR #2935

### CODE REVIEW

**Comment by tomkerkhove** [comment]
I was looking for `release_notes.md` but could not find it, did I look over it?

**Comment by michaelpeng36** [comment]
No, that file does not exist in the repository. I have updated the PR template.

**Review by michaelpeng36 — APPROVED** [review]
LGTM

**Comment by tomkerkhove** [comment]
Thank you @michaelpeng36!

**Pull request merged**
