### PR TITLE
Update templates.json.template with powershell related template files

### PR DESCRIPTION
**Pull request by daxian-dbw**
Update `templates.json.template` with PowerShell HTTP trigger template files.

This PR and #706 together will provide a relatively complete local experience using func CLI with PowerShell worker:
```
func init --worker-runtime powershell
func new -l powershell -t HttpTrigger -n MyHttpTrigger
func start
```

### CODE REVIEW

**Comment by daxian-dbw** [comment]
cc @SteveL-MSFT @tylerl0706 @pragnagopa @asavaritayal

**Comment by ahmelsayed** [comment]
@soninaren I think this is conflicting with your latest template update.

**Comment by soninaren** [comment]
lets hold this off until we are out of ask mode.

**Comment by soninaren** [comment]
I will merge the related template PR https://github.com/Azure/azure-functions-templates/pull/736 and generate an updated template file.

**Comment by ahmelsayed** [comment]
@soninaren  This is no longer needed, right?

**Comment by soninaren** [comment]
@ahmelsayed yes we can close this. I have already added powershell templates

**Pull request closed without merging**
