### PR TITLE
Fixes C# project being built instead of F# project

### LINKED ISSUE #3171: Selecting dotnet isolated and F# created a C# project
When using the `func init` command to create a new dotnet isolated project and selecting F# as the language, a C# template is used for the output files:

```
vscode@007cb021b112:~/fsharp$ func init
Select a number for worker runtime:
1. dotnet
2. dotnet (isolated process)
3. node
4. python
5. powershell
6. custom
Choose option: 2
dotnet-isolated
Select a number for language:
1. c#-isolated
2. f#-isolated
Choose option: 2
f#-isolated

Writing /home/vscode/fsharp/.vscode/extensions.json
vscode@007cb021b112:~/fsharp$ ls
Program.cs  Properties  fsharp.csproj  host.json  local.settings.json
vscode@007cb021b112:~/fsharp$ func --version
4.0.4785
```

Note that I selected the `f#-isolated` option when choosing the language but the files on disk are from the C# template. There is an F# template (https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated) so it's likely that the `init` command isn't respecting the language selection.

### PR DESCRIPTION
**Pull request by auslavs**
### Issue describing the changes in this PR
resolves #3171

When using the `func init` command to create a new dotnet isolated project and selecting F# as the language, a C# template is used for the output files.

This change passes the language preference argument to the `dotnet new func` when F# is selected only.
I have omitted passing the language preference when C# is selected as this is the default language and it is the current behavior.

There are some differences between the C# & F# templates which means we need to omit some of the arguments for example:
* The F# templates do not support the `--Framework` argument and is hardcode to `net6.0`
* The F# (non-isolate) template does not support the `--AzureFunctionsVersion` argument and is hard coded to `v4`

So the fix is less than ideal until the templates are brough into line with the C# versions, but this should allow F# developers to get started with Azure Functions.

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by auslavs** [comment]
@microsoft-github-policy-service agree

**Comment by parkeradam** [comment]
Please can this get looked at and merged. This is off the back of an issue from  Apr 14, 2021 (https://github.com/Azure/azure-functions-core-tools/issues/2549) which was then promoted to an issue by a MS employee (https://github.com/Azure/azure-functions-core-tools/issues/3171) and it says something that a community member has made this change for a substantial bug in the Azure CLI tooling. I for one would love to use F# for azure functions.

**Comment by bigjonroberts** [comment]
Wow, 7 months from the issue being reported and 10 weeks out from the fix submission and no one has even looked at this fix for a glaring issue.  Is anyone looking at the backlog of these community contributions?

@michaelpeng36 or @khkh-ms Ya'll should probably take a look at this.

**Comment by bigjonroberts** [comment]
@AnatoliB Have you looked at this one? ^^^

**Comment by bigjonroberts** [comment]
@aaronpowell Someone submitted a fix for the issue you reported.  Wonder if you can help push this one along?

**Comment by bigjonroberts** [comment]
@auslavs thanks for submitting this.  I hope that someone somewhere sees it and does something with it.  The lack of response on this PR is in indication that either:
- processes are broken here for reviewing community submissions
or
- no one cares?

I suspect it's the first option and I hope that someone sits up and takes notice and asks the product manager or lead here to help get these types of fixes in.

**Comment by auslavs** [comment]
Thanks @bigjonroberts for your support. From the number other issues raised in this repo it does look like they are a bit overwhelmed.

It is a shame that we can't get this one fixed as it is a blocker for anyone wishing to get started with Azure Functions in F#.

**Comment by grab-a-byte** [comment]
Could it be this isn't being looked at as its missing parts in the Pull Request checklist from the template? I se it at the bottom of the PR, does this need filled out before someone will take a look?

**Comment by auslavs** [comment]
@grab-a-byte good point. Hopefully, that is the issue. I should be able to take a look at this in the next day or so.

**Comment by auslavs** [comment]
It took me longer than I'd like to get back to this. I updated my branch and reviewed the code to see if I could add tests.
IMHO, that part of the code is not very testable, and I could not see any existing tests for the code path.
Please let me know if I'm mistaken. If pointed in the right direction, I'm happy to write the tests.

**Comment by bigjonroberts** [comment]
@michaelpeng36 @AnatoliB @khkh-ms @amamounelsayed 
Can any of you re-trigger the azure-functions-core-tools build (seems to be stuck) and are available to review this?

**Comment by auslavs** [comment]
@michaelpeng36 my guess is the build failed due to a transient error with the pipeline.
Is it possible to run it again? Thanks.

```
System.AggregateException : One or more errors occurred. (AZURE_MANAGEMENT_ACCESS_TOKEN is not defined in current environment)
---- System.Exception : AZURE_MANAGEMENT_ACCESS_TOKEN is not defined in current environment
```

**Comment by jviau** [comment]
@auslavs the failure is due to this being a fork - the current pipeline does not work for forks.

**Pull request closed without merging**
