### PR TITLE
update PowerShell Worker Version

### PR DESCRIPTION
**Pull request by tylerl0706**
Tons of good stuff inside :)

cc @pragnagopa @SteveL-MSFT @daxian-dbw @asavaritayal @soninaren

### CODE REVIEW

**Comment by ahmelsayed** [comment]
This doesn't require templates updates, right?

**Comment by tylerl0706** [comment]
My understanding is that the template deployment and the dockerfile deployment are separate. Is that not the case? 

We just had a few templates merged into the azure-functions-templates repo.

**Comment by tylerl0706** [comment]
Ah! Understood. Yes old templates (well, there's only one 😊) are compatible.

No coordination is needed between templates and worker.

**Comment by tylerl0706** [comment]
@ahmelsayed are there any blockers to merge this in?

**Pull request merged**
