### PR TITLE
updating .NET templates and updating .NET model prompts

### LINKED ISSUE #3603: Dotnet templates are behind for 5530
The current version of the templates used by the Core Tools in the latest version (5530) seems to be 4.0.2848, last updated [2023-10-18](https://github.com/Azure/azure-functions-core-tools/commit/43fb9ff2818c75585aa1fd700e86f7ed24cffd4c):

https://github.com/Azure/azure-functions-core-tools/blob/2f6887eea63affecbb87f90a71cc4265a060d170/build/Settings.cs#L22-L26

These need to be updated to 4.0.2945 which includes quite a few updates to both project and item templates.

### PR DESCRIPTION
**Pull request by mattchenderson**
resolves #3603

Also cleans up some label inconsistency and leads with the isolated worker model in prompting.

### Pull request checklist

* [X] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [X] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [X] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by mattchenderson** [comment]
I assert that the build errors are unrelated to my changes, as the same thing is happening in other PRs, and it comes from a code path that I did not touch.

**Review by khkh-ms — APPROVED** [review]

**Comment by mattchenderson** [comment]
@khkh-ms checking back on this. What's needed to get this one in?

**Comment by khkh-ms** [comment]
PR are now passing in the pipeline. I will do another try for the build. I will recommend that you get latest from v4.x into your branch if it is not working.

**Comment by mattchenderson** [comment]
@khkh-ms, I pushed a rebase, but still seems off, and I see the same happening for "current build" too.

**Comment by khuramhd** [comment]
Thanks! I will run the failing tests locally today/tomorrow and fix the tests if needed.

**Comment by mattchenderson** [comment]
Any updates @khkh-ms ?

**Comment by mattchenderson** [comment]
This PR now removes a test, reintroduction of which is related to #3644

**Pull request merged**
