### PR TITLE
Updated JavaWorker, NodeJsWorker, PowerShellWorker.PS6, PowerShellWor…

### PR DESCRIPTION
**Pull request by kashimiz**
…ker.PS7, and WebJobs.Script.WebHost references.

### CODE REVIEW

**Comment by Francisco-Gamino** [comment]
@kashimiz -- are we also updating the PowerShell worker?

**Comment by kashimiz** [comment]
@francisco-gamino This update brings references in line with the release/3.0-hotfix-79 branch, which doesn't change the PowerShell workers: https://github.com/Azure/azure-functions-host/blob/a797bc2afdd68bf15cd46e5ff409220f35050cc2/src/WebJobs.Script/WebJobs.Script.csproj#L47

The next release after this will merge the v3.x branch into the release/3.0 branch.

**Comment by kashimiz** [comment]
Pausing on this to update with new build.

**Comment by fabiocav** [comment]
Closing stale PR

**Pull request closed without merging**
