### PR TITLE
Inject language worker debug options as environment variables

### PR DESCRIPTION
**Pull request by pragnagopa**
Workaround for https://github.com/Azure/azure-functions-host/issues/2894
More details: https://github.com/Microsoft/vscode-azurefunctions/issues/387

### CODE REVIEW

**Comment by pragnagopa** [comment]
@fabiocav - Version test in the CI has failed. I see you have a PR out to update. Should I wait to merge this PR?

**Comment by fabiocav** [comment]
I merged that. If you rebase, you should have a green build.

**Comment by pragnagopa** [comment]
@fabiocav - Please start the release process for CLI.

**Comment by fabiocav** [comment]
Thanks. I'l also file an issue to track the bug that broke this and required the workaround.

**Pull request merged**
