### PR TITLE
Fix install command for non windows platform

### PR DESCRIPTION
**Pull request by fumiya-kume**
before command cannot install in macOS.
so fix.

### CODE REVIEW

**Comment by wilsonge** [comment]
I can use the existing command to install for mac and do not need this

**Comment by fumiya-kume** [comment]
Thanks for review.
In this document write it.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

>When installing on macOS and Linux, you may need to include the `unsafe-perm` flag, as follows:
>```bash
>sudo npm install -g azure-functions-core-tools@core --unsafe-perm true
>```

which one is correct?

**Comment by wilsonge** [comment]
It does say `may` :P I'm not sure what the condition is (maybe a microsoft employee can clarify) - but it's definitely not a requirement for me. I should add I guess that maybe the difference is I don't run it with sudo - I just use 

`npm install -g azure-functions-core-tools@core`

**Comment by ahmelsayed** [comment]
That's due to npm behavior of post install script. if you `sudo` the npm command, which is the default on macs and linux, you most likely need `--unsafe-perm`, unless you have also set the npm user. 

Basically by default when you `sudo npm`, it only runs its own code in sudo, and any postinstall script with `nobody` user by default. You can either change npm to not require sudo for global packages, or change the default user it uses after install to something other than `nobody` to allow postinstall script to have an id. 

[`--unsafe-perm`](https://docs.npmjs.com/misc/config#unsafe-perm) tells npm to run the postinstall script as sudo as well. Something you probably don't wanna do lightly if you're installing a package you don't completely trust. 

Since this cli supports running javascript functions, but is not itself javascript, and can be a bit large, I host the actual content on a CDN and [download it a postinstall script](https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/npm/lib/install.js#L22) and for that script to be able to put the files in the default npm dir it needs to have access to it. 
I hope that makes sense. It took me a while to figure it out myself since it works differently on Windows. 

Thanks @fumiya-kume for your contribution. Would you mind also adding the bit from the docs also on top of the command as part of this PR 

>When installing on macOS and Linux, you may need to include the `unsafe-perm` flag, as follows:

**Comment by fumiya-kume** [comment]
@ahmelsayed Thanks comments.
I added bit from the doc.

**Comment by ahmelsayed** [comment]
thanks @fumiya-kume!

**Pull request merged**
