### PR TITLE
Add table to binding package map and update Storage extension version

### PR DESCRIPTION
**Pull request by anthonychu**

### CODE REVIEW

**Comment by anthonychu** [comment]
@soninaren Checking in to see how this is going and if I should bump this up to 3.0.5.

**Comment by ahmelsayed** [comment]
@soninaren Can you please take a look at this PR and merge it if it looks good to you?

**Comment by anthonychu** [comment]
Resolved merge conflict

**Comment by soninaren** [comment]
> @soninaren Checking in to see how this is going and if I should bump this up to 3.0.5.

Cannot update the storage version right now. Have some other work linked to this for which i need to keep the extension versions as is across all repos.

**Pull request merged**
