### PR TITLE
Adds KEDA support for default connection fields for some Azure triggers

### PR DESCRIPTION
**Pull request by prqgdbc**
Adds Keda support for default connection variable names for Azure Service Bus, Azure Queue Storage, and Azure Blob Storage triggers.

This change will cause the PopulateMetadataDictionary method of KedaV2Resource to default to AzureWebJobsStorage for Azure Queue Storage, and Azure Blob Storage triggers, and AzureWebJobsServiceBus in the case of Azure Service Bus triggers.

This will allow users to not have to specify their connection variable name if they intend to use supported defaults.

Resolves Azure/azure-functions-core-tools#2404

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM.

**Comment by tomkerkhove** [comment]
@pragnagopa We should get some unit tests setup for the Kubernetes side of things

**Comment by pragnagopa** [comment]
@prqgdbc  - Thanks for the PR. Please rebase your commits on top of v3.x branch

@tomkerkhove - Assigned Unit test issue to next sprint. Thanks for the reminder.

**Review by pragnagopa — APPROVED** [review]

**Pull request merged**
