### PR TITLE
add support for ClusterIp / NodePort / LoadBalancer on kubernetes

### PR DESCRIPTION
**Pull request by acesyde**
- Add support for ClusterIp / NodePort / LoadBalancer
- Add missing await on deployment
- Add output of deployment (must be better for debugging on k8s)
- Add CultureInfo for double to string (not work if you compile on french computer...)
- Add constant for values instead of string (not repeat your self)
- #742

### CODE REVIEW

**Comment by acesyde** [comment]
@ahmelsayed this PR is ready to merge but build doesn't work :(

**Comment by ahmelsayed** [comment]
Sorry just taking a look at this PR now. Would you mind updating your branch since the diff is very messy

**Comment by acesyde** [comment]
@ahmelsayed it's ok now :)

**Comment by ahmelsayed** [comment]
very sorry for the very long delay in getting back to you @acesyde. I wasn't very familiar with kubernetes and needed to learn a bit more about it. I pulled your change into another bigger change I'm making to improve the kubernetes story through the tooling here https://github.com/Azure/azure-functions-core-tools/pull/1266 

I'm closing this PR since it's included in the above one.

**Pull request closed without merging**
