### PR TITLE
DurableFunctions Delete Task Hub - Added PartitionCount lookup from host.json

### PR DESCRIPTION
**Pull request by gorillapower**
### Issue describing the changes in this PR

When deleting a Task hub via the CLI, the default hardcoded partition count is used (currently 4). This means that only the default number of queues are deleted, resulting in orphaned queues in the storage account.

This pull request uses the partition count specified in the host.json if it is present.

### Pull request checklist

* [ X] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ X] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by davidmrdavid** [comment]
@michaelpeng36 - can you please give this a look?

**Comment by davidmrdavid** [comment]
I've been able to repro the issue that this PR aims to fix. So I can confirm the presence of the bug. That said, I'll need help to validate that the PR fixes core tools.

Please see [this](https://github.com/Azure/azure-functions-durable-extension/issues/2130#issuecomment-1091754371) comment to reproduce the error.

**Comment by michaelpeng36** [comment]
Thanks for the contribution and for surfacing this issue @gorillapower. Would you be able to make your target branch `v4.x` instead of `dev`?

**Comment by gorillapower** [comment]
> Thanks for the contribution and for surfacing this issue @gorillapower. Would you be able to make your target branch `v4.x` instead of `dev`?

Sure thing. Is it correct now?

**Comment by michaelpeng36** [comment]
Thanks for the prompt action @gorillapower. Actually, it looks like this is pulling in a couple other changes that we would like to keep separate. Would you be able to do the following?

1. On your fork, checkout the `v4.x` branch and run the command `git cherry-pick <sha256>`, where `<sha256>` is the commit hash of your change.
2. Create a new PR against the `v4.x` branch of this repository.

**Comment by gorillapower** [comment]
@michaelpeng36  thanks for info! I have created new pull request here #3020

**Comment by michaelpeng36** [comment]
@TroyWitthoeft, Core Tools V4 is available on Chocolatey under the name `azure-functions-core-tools`, as seen here: https://community.chocolatey.org/packages/azure-functions-core-tools

**Pull request closed without merging**
