### PR TITLE
Fixing the error in the func new action with extension bundles is configured

### PR DESCRIPTION
**Pull request by soninaren**

### CODE REVIEW

**Comment by soninaren** [comment]
@ahmelsayed need to add it to the current release. Some docs are blocked on it.

**Comment by ahmelsayed** [comment]
Can you set it in `Main` instead?

**Comment by ahmelsayed** [comment]
Only set it if it's not already set.

**Comment by ahmelsayed** [comment]
also move it to a method call maybe `SetCoreToolsEnvironmentVariables` or something like that.

**Pull request merged**
