### PR TITLE
fix: gozip across different host OS architectures

### PR DESCRIPTION
**Pull request by mxschmitt**
Before for e.g. macOS or Windows the `gozip` executable did not match the target OS architecture. This PR fixes that:

image

### Issue describing the changes in this PR

Fixes https://github.com/Azure/azure-functions-core-tools/issues/3648

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

cc @arroyc

### CODE REVIEW

**Review by fschlegelone — APPROVED** [review]
LGTM!

**Comment by drew1326** [comment]
@khkh-ms / @amamounelsayed Please review/accept this fix - this is a blocker for me on an M2 Mac. Thanks!

**Comment by fschlegelone** [comment]
@drew1326 as a temporary workaround, you can manually build the gozip binary & replace it.

**Comment by mxschmitt** [comment]
@fabiocav pushed a fix (https://github.com/Azure/azure-functions-core-tools/pull/3650/commits/481986aa63e37eed5be72a42d9216254c2ba1319) which started failing after https://github.com/Azure/azure-functions-core-tools/commit/a0fe7af153470e291ba316c9840a324ae2dc9923.

**Comment by fabiocav** [comment]
Thank you, @mxschmitt ! Re-running the build to make sure we're green.

**Review by fabiocav — APPROVED** [review]

**Comment by fabiocav** [comment]
Thank you, @mxschmitt , for the contribution and the patience!

**Comment by ldibanyez** [comment]
Is there a nightly build from where I can grab the correct gozip executable? Current latest 4.06280 seems to be affected by the bug.

**Pull request merged**
