### PR TITLE
Resolve Key Vault references using local identity

### PR DESCRIPTION
**Pull request by anthonychu**
#933
https://github.com/Azure/azure-functions-host/issues/3907

Supports both `@Microsoft.KeyVault` syntaxes. Version is optional.

@mattchenderson @fabiocav

### CODE REVIEW

**Comment by avitryhard** [comment]
Is this resolved? I'm so happy if we have this feature for local. Because it's so important for debug testing.

**Comment by avitryhard** [comment]
> Is this resolved? I'm so happy if we have this feature for local. Because it's so important for debug testing.

@anthonychu

**Comment by vmcbaptista** [comment]
Any news on this @anthonychu @fabiocav @mattchenderson?

**Comment by fabiocav** [comment]
@anthonychu going through some of the open items and noticed this was still open. Would you be able to rebase this so we can get this reviewed and in? thanks!

**Comment by Cdoherty95** [comment]
Just wondering any news on this @fabiocav?

**Comment by aegpoadan** [comment]
I've created a new PR that contains the functionality in this PR, and is up to date with the v3.x branch: https://github.com/Azure/azure-functions-core-tools/pull/2806

**Comment by michaelpeng36** [comment]
Closing this PR, as issue #933 was resolved by #2806 and #2924.

**Pull request closed without merging**
