### PR TITLE
add command to install functions using winget

### PR DESCRIPTION
**Pull request by mverbaas**
Please accept this PR with a very small addition of how to install the Azure Function Core Tools using Microsoft Winget.

### CODE REVIEW

**Review by michaelpeng36 — APPROVED** [review]
LGTM

**Comment by michaelpeng36** [comment]
@mverbaas, would you be able to remove one of the tick characters at end of the `bash` clause? I believe there are supposed to be three rather than four. Once that is done, and the CLA requirements are met, I will merge and port this over to `v3.x` and `v4.x`.

**Comment by mverbaas** [comment]
@michaelpeng36 , I don't think I can. I deleted my fork. And local branches, unfortunately. I've been looking to change this in browser, but can't find the options. If you don't have an option, feel free to reject the PR.

**Comment by michaelpeng36** [comment]
@mverbaas, in this case, I will create a new PR based on this one. Nonetheless, thank you for the contribution!

**Pull request closed without merging**
