### PR TITLE
Adding a cli flag to start with full exception stack traces

### PR DESCRIPTION
**Pull request by aaronpowell**
This addresses #1557 by adding a new CLI flag so you can do `func start --verbose-errors` and get full stack traces in the logging when an internal component fails.

### CODE REVIEW

**Comment by ankitkumarr** [comment]
@aaronpowell, we have a debug environment variable `CLI_DEBUG` that can be set to `1` or `true`.

Would you mind updating your PR to leverage that? You can check whether or not we are in debug mode by calling this https://github.com/Azure/azure-functions-core-tools/blob/48f45fb402663fd95b9317c1f0a32c977cd1e40b/src/Azure.Functions.Cli/Common/StaticSettings.cs#L8

This way we don't have to expose another parameter and make it consistent with our debug settings.

**Comment by aaronpowell** [comment]
@ankitkumarr I didn't realise that flag existed. I'll update to use it.

**Comment by aaronpowell** [comment]
@ankitkumarr Updated to use the flag from settings.

**Comment by M0ns1gn0r** [comment]
@brettsam can you review? The changes are small.

**Comment by brettsam** [comment]
Can you rebase this onto `dev` so it can be cleanly merged? Changes look good -- once it's rebased we can get it in.

**Comment by aaronpowell** [comment]
@brettsam - done a rebase against the `dev` branch and force-pushed to this one to update the commit history.

**Comment by brettsam** [comment]
@aaronpowell -- can you squash these down to a single commit? That should force the CI to run again (I don't know why it's stalled...)

**Comment by ankitkumarr** [comment]
@brettsam, I think we don't allow CI runs from a fork that's not ours for security reasons.

**Comment by aaronpowell** [comment]
Would you still like a squish commit done or are you happy with it as it stands?

**Comment by brettsam** [comment]
Yes, please squash, then I'll go ahead and merge it. Thanks!

**Comment by aaronpowell** [comment]
Squished now :)

**Comment by ksurakka** [comment]
Thx @aaronpowell , used your repo as a workaround until this gets released.

@brettsam is there some problem with the pipeline?

**Comment by brettsam** [comment]
I'm sorry, I thought we had merged this already! @aaronpowell -- it looks like there's a conflict in the dev branch now. Would you be able to rebase and address the conflicts? @ankitkumarr and I can help get this merged ASAP.

**Comment by aaronpowell** [comment]
@brettsam Sorry, did it as a merge not a rebase, is that ok?

**Comment by brettsam** [comment]
We try to avoid merges from forks -- but let me see if I can grab this and get it in for you with a merge. Thanks for all the help here!

**Comment by brettsam** [comment]
Closing this in favor of #1701.

**Comment by aaronpowell** [comment]
All good, I just hit the wrong button. Next time I'll ensure I rebase.

**Pull request closed without merging**
