### PR TITLE
Generating the dockerfile when runtime is powershell

### PR DESCRIPTION
**Pull request by guojian83**
Please see: DockerFile PowerShell #1389

### CODE REVIEW

**Comment by Francisco-Gamino** [comment]
Hi @guojian83, thank you for sending this. Could you please rebase push again? Please only include the commit for your code change. Thanks.

@ankitkumarr : Could you please take a quick look as you are more familiar with this code base? Thanks.

**Comment by guojian83** [comment]
Hi @Francisco-Gamino,

It's getting too messy now even the rebase got many conflicts. I am going to close this one and start a new one.

Regards,
Jian

**Comment by Francisco-Gamino** [comment]
Sounds good @guojian83. Thank you.

**Comment by guojian83** [comment]
New PR: #1513

**Pull request closed without merging**
