### PR TITLE
Retain Azure Files settings for Linux consumption remote build

### PR DESCRIPTION
**Pull request by balag0**
Reverting https://github.com/Azure/azure-functions-core-tools/pull/1437/files which was originally required to workaround a limitation.

### CODE REVIEW

**Review by pgombar — APPROVED** [review]

**Comment by pgombar** [comment]
Let's hold on with this merge until we have a better logic for disabling portal editing for Linux Consumption.

**Comment by pragnagopa** [comment]
Tagging @takyyon 

@pgombar  / @takyyon - Are the UX changes done? Can we merge this PR in?

**Comment by pgombar** [comment]
@balag0 @pragnagopa this can be merged now. The logic on the UX will handle this case. Thanks 😄

**Comment by pragnagopa** [comment]
@pgombar - Can you confirm if UX changes are deployed to prod?

**Comment by pragnagopa** [comment]
@balag0 - ETA for Portal updates to be deployed to prod is End of next week. Please rebase this PR.

**Review by pragnagopa — APPROVED** [review]

**Pull request merged**
